 git subtree push -P G1ANT.Addon.GoogleDocs https://g1ant.kilnhg.com/Code/G1ANT-Addon-GoogleDocs/Group/Production.git master
 git subtree push -P G1ANT.Addon.IExplorer https://g1ant.kilnhg.com/Code/G1ANT-Addon-IExplorer/Group/Production.git master
 git subtree push -P G1ANT.Addon.Images https://g1ant.kilnhg.com/Code/G1ANT-Addon-Images/Group/Production.git master
 git subtree push -P G1ANT.Addon.Mscrm https://g1ant.kilnhg.com/Code/G1ANT-Addon-Mscrm/Group/Production.git master
 git subtree push -P G1ANT.Addon.MSOffice https://g1ant.kilnhg.com/Code/G1ANT-Addon-MSOffice/Group/Production.git master
 git subtree push -P G1ANT.Addon.Net https://g1ant.kilnhg.com/Code/G1ANT-Addon-Net/Group/Production.git master
 git subtree push -P G1ANT.Addon.Ocr https://g1ant.kilnhg.com/Code/G1ANT-Addon-Ocr/Group/Production.git master
 git subtree push -P G1ANT.Addon.Ocr.AbbyyFineReader https://g1ant.kilnhg.com/Code/G1ANT-Addon-Ocr-AbbyyFineReader/Group/Production.git master
 git subtree push -P G1ANT.Addon.OCR.Tesseract https://g1ant.kilnhg.com/Code/G1ANT-Addon-OCR-Tesseract/Group/Production.git master
 git subtree push -P G1ANT.Addon.Selenium https://g1ant.kilnhg.com/Code/G1ANT-Addon-Selenium/Group/Production.git master
 git subtree push -P G1ANT.Addon.Watson https://g1ant.kilnhg.com/Code/G1ANT-Addon-Watson/Group/Production.git master
 git subtree push -P G1ANT.Addon.Xlsx https://g1ant.kilnhg.com/Code/G1ANT-Addon-Xlsx/Group/Production.git master